#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=64
#SBATCH -o e_minimization.txt
#SBATCH -e e_minimization.txt

module load QuantumESPRESSO/7.2-intel-2022a

mpirun -np 64 cp.x -inp /home/adamh94/MoS2/cp_electronic_minimization.in > /home/adamh94/MoS2/output/cp_electronic_minimization.out
