#!/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=64
#SBATCH -o slurm_relax.txt
#SBATCH -e slurm_relax.txt

module load QuantumESPRESSO/7.2-intel-2022a

mpirun -np 64 cp.x -inp /home/adamh94/MoS2/cp.in > /home/adamh94/MoS2/output/cp.out
