#!/bin/bash
#SBATCH -N 4
#SBATCH --ntasks-per-node=64
#SBATCH -o slurm_scf.txt
#SBATCH -e slurm_scf.txt

module load QuantumESPRESSO/7.2-intel-2022a

mpirun -np 256 cp.x -inp cp_electronic_minimization.in > cp_electronic_minimization.out
